spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/Ecommerce-orderDB
    username: postgres
    password: challanger

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8081